export const siteData = {
  name: 'Salim Khadir',
  initials: 'SK',
  role: 'Fullstack & AI Engineer',
  location: 'Île-de-France, France 🇫🇷',
  email: 'salim.khadir@email.com',
  github: 'https://github.com/SalimKH5',
  linkedin: 'https://linkedin.com/in/salimkhadir',
  available: true,

  bio: [
    "Hey, I'm Salim — a fullstack developer and data engineer based in France with over 3 years of professional experience. I specialize in bridging the gap between robust web architectures and intelligent, AI-driven systems.",
    "I build highly performant, scalable applications using Next.js on the frontend, and I architect secure, enterprise-grade backends using .NET and Python.",
    "Currently, I am heavily focused on the intersection of Data Engineering and Artificial Intelligence. I actively integrate Large Language Models (like Claude) and RAG (Retrieval-Augmented Generation) pipelines into modern applications, turning raw data into interactive, actionable insights.",
  ],

  stats: [
    { num: '3+', label: 'Years Exp.' },
    { num: 'AI/LLM', label: 'Integration' },
    { num: 'M2', label: 'Data Eng.' },
  ],

  info: [
    { key: 'Location', value: 'Île-de-France, France 🇫🇷' },
    { key: 'Focus', value: 'Web Engineering & AI Systems (RAG/LLMs)' },
    { key: 'Languages', value: 'French · English · Arabic' },
    { key: 'Education', value: "Master's in Data Engineering" },
    { key: 'Status', value: 'Open to work', accent: 'teal' },
  ],

  skills: [
    {
      name: 'AI & Data Engineering',
      icon: 'ti-brain',
      color: 'blue',
      tags: ['Python', 'RAG (Retrieval-Augmented Gen)', 'Claude LLM', 'OpenAI', 'Vector Embeddings', 'Pandas', 'Apache Spark'],
    },
    {
      name: 'Backend Core',
      icon: 'ti-server',
      color: 'teal',
      tags: ['.NET', 'C#', 'Python', 'FastAPI', 'Node.js', 'NestJS', 'REST', 'JWT Auth'],
    },
    {
      name: 'Frontend Modern',
      icon: 'ti-layout',
      color: 'purple',
      tags: ['Next.js', 'React.js', 'TypeScript', 'Tailwind CSS', 'Redux', 'Framer Motion'],
    },
    {
      name: 'Database',
      icon: 'ti-database',
      color: 'coral',
      tags: ['PostgreSQL', 'Typesense', 'MySQL', 'MongoDB', 'Redis', 'Prisma'],
    },
    {
      name: 'DevOps & Architecture',
      icon: 'ti-topology-complex',
      color: 'accent',
      tags: ['Medallion Architecture', 'Docker', 'GitHub Actions', 'Vercel', 'Linux', 'Git'],
    },
  ],

  projects: [
    {
      id: 0,
      title: 'MunchMate & MunchMate Pro',
      description:
        'A comprehensive dual-sided restaurant management platform. End-users can discover local spots, book tables, and order online via the main portal. Meanwhile, restaurant owners utilize the powerful admin dashboard to create their listings, manage menus, and handle incoming reservations. The platform is powered by a robust .NET backend secured with JWT authentication.',
      icon: 'ti-tools-kitchen-2',
      color: 'coral',
      featured: true,
      github: 'https://github.com/SalimKH5',
      live: 'https://munchmate.salimfree.com/',
      adminUrl: 'https://pro.salimfree.com/',
      image: 'https://munchmate.salimfree.com/_next/image?url=%2FBanner3.jpg&w=3840&q=75',
      stack: ['Next.js', 'TypeScript', '.NET', 'JWT Auth', 'REST API', 'Tailwind CSS', 'PostgreSQL'],
      highlights: [
        'Dedicated admin dashboard (Pro) for restaurant management',
        'Secure backend architecture built with .NET and JWT',
        'Table booking with instant confirmation',
        'Online ordering — delivery & pickup',
        'Multi-restaurant menu & category browsing',
      ],
    },
    {
      id: 1,
      title: 'AI Knowledge Assistant (RAG Engine)',
      description: 'An intelligent enterprise search and chat platform leveraging Retrieval-Augmented Generation (RAG). It ingests document repositories, generates semantic embeddings, and uses the Claude LLM to provide highly accurate, context-aware answers to user queries.',
      icon: 'ti-robot',
      color: 'blue',
      featured: true,
      github: 'https://github.com/SalimKH5',
      live: '#',
      image: '', // You can add an image URL here later
      stack: ['Python', 'Claude LLM', 'RAG', 'Typesense', 'Next.js', 'FastAPI'],
      highlights: [
        'Semantic search using high-dimensional vector embeddings',
        'Contextual answering powered by Claude LLM',
        'Decoupled architecture with Python API and Next.js frontend',
      ],
    },
    {
      id: 2,
      title: 'Snaply',
      description: 'A fully functional social media platform clone with user authentication, photo uploads, and real-time interactions. Leverages Next.js API routes and server-side rendering for optimal performance.',
      icon: 'ti-brand-instagram',
      color: 'purple',
      featured: false,
      github: 'https://github.com/SalimKH5/Snaply',
      live: 'https://snaply-git-main-khadir-salims-projects.vercel.app/',
      image: 'https://firebasestorage.googleapis.com/v0/b/portfolio-af3bf.appspot.com/o/instagrame%20clone.png?alt=media&token=55d1fc1e-bc3a-4147-8331-41a90dae62cd',
      stack: ['Next.js', 'React.js', 'MongoDB', 'Tailwind CSS', 'TypeScript'],
      highlights: [],
    },
    {
      id: 3,
      title: 'REST Countries',
      description: 'A web app to explore and filter countries by population, region, and language. Built with React.js and TypeScript for a responsive, interactive data visualization experience.',
      icon: 'ti-world',
      color: 'teal',
      featured: false,
      github: 'https://github.com/SalimKH5/rest-countries-master',
      live: 'https://rest-countries-master-git-main-khadir-salims-projects.vercel.app/',
      image: 'https://firebasestorage.googleapis.com/v0/b/portfolio-af3bf.appspot.com/o/rest%20country.png?alt=media&token=1d8cded7-e98c-4d3b-93e0-60402faae152',
      stack: ['React.js', 'TypeScript', 'REST API', 'Tailwind CSS'],
      highlights: [],
    },
    {
      id: 4,
      title: 'YouTube Clone',
      description: 'A video streaming interface built with React.js and an external API. Features video playback, dynamic search functionality, and an optimized front-end architecture.',
      icon: 'ti-brand-youtube',
      color: 'accent',
      featured: false,
      github: 'https://github.com/SalimKH5/Youtube-clone',
      live: 'https://gregarious-monstera-5e42e6.netlify.app/',
      image: 'https://firebasestorage.googleapis.com/v0/b/portfolio-af3bf.appspot.com/o/youtube.png?alt=media&token=3bbadc37-f105-42e9-b96d-11b1eb9ef8f8',
      stack: ['React.js', 'REST API', 'CSS3', 'HTML5'],
      highlights: [],
    },
    {
      id: 5,
      title: 'Static Job Listings',
      description: 'A job listings page featuring complex state management for filtering by title, location, and role type. Designed for an efficient and instant search experience.',
      icon: 'ti-briefcase',
      color: 'purple',
      featured: false,
      github: 'https://github.com/SalimKH5/static-job-listings-master',
      live: 'https://salimkh5.github.io/static-job-listings-master/',
      image: 'https://firebasestorage.googleapis.com/v0/b/portfolio-af3bf.appspot.com/o/static-job-listings.png?alt=media&token=8a8beb9d-e48f-4efd-b835-2f2b50ee6ccd',
      stack: ['React.js', 'CSS3', 'HTML5'],
      highlights: [],
    },
  ],

  experience: [
    {
      period: 'Oct 2024 — Present',
      type: 'Full-time',
      role: 'Fullstack Developer',
      company: "La Plume d'or et d'argent",
      location: '21 rue Gambetta, Houilles, Île-de-France',
      bullets: [
        'Development and optimization of the company’s digital platforms.',
        'Architected responsive, secure, and user-friendly backend modules.',
        'Ensured high performance and reliability across the web stack.',
      ],
    },
    {
      period: 'Oct 2023 — Mar 2024',
      type: 'Internship',
      role: 'Frontend Developer',
      company: 'Immersive Digital Développement (IDD)',
      location: 'Cheraga, Algeria',
      bullets: [
        'Created intuitive and engaging user interfaces utilizing Next.js.',
        'Built dynamic and highly responsive web solutions for client-facing applications.',
        'Collaborated closely with design and engineering teams to refine UX/UI architectures.',
      ],
    },
    {
      period: 'Aug 2023 — Oct 2023',
      type: 'Freelance',
      role: 'Fullstack Developer',
      company: 'Algitech.sol',
      location: 'Remote',
      bullets: [
        'Developed essential backend logic and database structures for an e-commerce platform.',
        'Optimized data queries and improved overall application loading times.',
      ],
    },
  ],

  education: [
    {
      period: 'Oct 2024 — Present',
      degree: "Master's 2 — Data Engineering",
      institution: 'Digital School of Paris',
      icon: 'ti-school',
    },
    {
      period: 'Apr 2024 — Sep 2024',
      degree: "Master's 1 — Web Architecture",
      institution: 'Digital School of Paris',
      icon: 'ti-school',
    },
    {
      period: 'Sep 2021 — Jul 2023',
      degree: "Master's Degree — Bioinformatics",
      institution: 'USTHB — University of Science and Technology, Algeria',
      icon: 'ti-microscope',
    },
    {
      period: 'Jun 2021',
      degree: "Bachelor's Degree — Computer Science",
      institution: 'USTHB — University of Science and Technology, Algeria',
      icon: 'ti-device-desktop',
    },
  ],
};